#pragma once

#ifndef DUNGEON_X_DIM
#define DUNGEON_X_DIM 80
#endif
#ifndef DUNGEON_Y_DIM
#define DUNGEON_Y_DIM 21
#endif

#ifndef DUNGEON_ROOM_MIN_X
#define DUNGEON_ROOM_MIN_X 4
#endif
#ifndef DUNGEON_ROOM_MIN_Y
#define DUNGEON_ROOM_MIN_Y 3
#endif
#ifndef DUNGEON_ROOM_MAX_X
#define DUNGEON_ROOM_MAX_X 17
#endif
#ifndef DUNGEON_ROOM_MAX_Y
#define DUNGEON_ROOM_MAX_Y 11
#endif

#ifndef DUNGEON_MIN_NUM_ROOMS
#define DUNGEON_MIN_NUM_ROOMS 6
#endif
#ifndef DUNGEON_MAX_NUM_ROOMS
#define DUNGEON_MAX_NUM_ROOMS 9
#endif

#ifndef DUNGEON_PERLIN_SCALE_X
#define DUNGEON_PERLIN_SCALE_X 0.15f
#endif
#ifndef DUNGEON_PERLIN_SCALE_Y
#define DUNGEON_PERLIN_SCALE_Y 0.3f
#endif

#ifndef DUNGEON_MIN_NUM_MONSTERS
#define DUNGEON_MIN_NUM_MONSTERS 1
#endif

#ifndef DUNGEON_MAX_NUM_MONSTERS
#define DUNGEON_MAX_NUM_MONSTERS 16
#endif


#ifndef DUNGEON_PRINT_HARDNESS
#define DUNGEON_PRINT_HARDNESS 0
#endif

#ifndef DUNGEON_PRINT_BORDER
#define DUNGEON_PRINT_BORDER 0
#endif

#ifndef DUNGEON_FILE_NAME
#define DUNGEON_FILE_NAME "/dungeon"
#endif

#ifndef LEVEL_ITERATION_TIME_US
#define LEVEL_ITERATION_TIME_US 250000
#endif
