#pragma once

#ifndef DUNGEON_X_DIM
#define DUNGEON_X_DIM 80
#endif
#ifndef DUNGEON_Y_DIM
#define DUNGEON_Y_DIM 21
#endif

#ifndef DUNGEON_ROOM_MIN_X
#define DUNGEON_ROOM_MIN_X 4
#endif
#ifndef DUNGEON_ROOM_MIN_Y
#define DUNGEON_ROOM_MIN_Y 3
#endif
#ifndef DUNGEON_ROOM_MAX_X
#define DUNGEON_ROOM_MAX_X 17
#endif
#ifndef DUNGEON_ROOM_MAX_Y
#define DUNGEON_ROOM_MAX_Y 11
#endif

#ifndef DUNGEON_MIN_NUM_ROOMS
#define DUNGEON_MIN_NUM_ROOMS 6
#endif
#ifndef DUNGEON_MAX_NUM_ROOMS
#define DUNGEON_MAX_NUM_ROOMS 9
#endif

#ifndef DUNGEON_MIN_NUM_EACH_STAIR
#define DUNGEON_MIN_NUM_EACH_STAIR 1
#endif
#ifndef DUNGEON_MAX_NUM_EACH_STAIR
#define DUNGEON_MAX_NUM_EACH_STAIR 3
#endif

#ifndef DUNGEON_PERLIN_SCALE_X
#define DUNGEON_PERLIN_SCALE_X 0.15f
#endif
#ifndef DUNGEON_PERLIN_SCALE_Y
#define DUNGEON_PERLIN_SCALE_Y 0.3f
#endif

#ifndef DUNGEON_MIN_NUM_MONSTERS
#define DUNGEON_MIN_NUM_MONSTERS 1
#endif
#ifndef DUNGEON_MAX_NUM_MONSTERS
#define DUNGEON_MAX_NUM_MONSTERS 16
#endif

#ifndef DUNGEON_MIN_NUM_ITEMS
#define DUNGEON_MIN_NUM_ITEMS 10
#endif
#ifndef DUNGEON_MAX_NUM_ITEMS
#define DUNGEON_MAX_NUM_ITEMS 25
#endif

#ifndef DUNGEON_FILE_NAME
#define DUNGEON_FILE_NAME "dungeon"
#endif

#ifndef MONSTER_DESC_FILE_NAME
#define MOSNTER_DESC_FILE_NAME "monster_desc.txt"
#endif

#ifndef OBJECT_DESC_FILE_NAME
#define OBJECT_DESC_FILE_NAME "object_desc.txt"
#endif




#define DUNGEON_TOTAL_CELLS     (DUNGEON_X_DIM * DUNGEON_Y_DIM)

#define DUNGEON_MAP_WIN_X_DIM   DUNGEON_X_DIM
#define DUNGEON_MAP_WIN_Y_DIM   DUNGEON_Y_DIM
#define DUNGEON_MAP_WIN_X_OFF   0
#define DUNGEON_MAP_WIN_Y_OFF   1

#define MONLIST_WIN_X_DIM       (DUNGEON_X_DIM - 2)
#define MONLIST_WIN_Y_DIM       (DUNGEON_Y_DIM - 2)
#define MONLIST_WIN_X_OFF       (DUNGEON_MAP_WIN_X_OFF + 1)
#define MONLIST_WIN_Y_OFF       (DUNGEON_MAP_WIN_Y_OFF + 1)

#define INVENTORY_WIN_X_DIM       (DUNGEON_X_DIM - 2)
#define INVENTORY_WIN_Y_DIM       (DUNGEON_Y_DIM - 2)
#define INVENTORY_WIN_X_OFF       (DUNGEON_MAP_WIN_X_OFF + 1)
#define INVENTORY_WIN_Y_OFF       (DUNGEON_MAP_WIN_Y_OFF + 1)

#define MONLIST_PROXIMITY_GRADIENT  {1000, 20, 20}, {40, 1000, 40}
#define DUNGEON_HARDNESS_GRADIENT   {700, 0, 600}, {200, 1000, 400}
#define DUNGEON_WEIGHTMAP_GRADIENT  {400, 100, 1000}, {400, 1000, 100}
